version: '3.7'

volumes:
  mysqllab:
  sqllab:  

services:
    library:
        build: . 
        ports:
            - "5004:5004"
            - "50059:50059"
        volumes:
            - .:/code
        command: bash -c "pm2 start ./consumer.py && pm2 start app.py --no-daemon" 
        networks:
          - server_kafka_net
    mysqldb:
        command: mysqld
        image: mysql:5.7
        ports:
          - '3307:3306'
        environment:
           MYSQL_DATABASE: 'library2'
           MYSQL_USER: 'lab'
           MYSQL_PASSWORD: 'osmentos'
           MYSQL_ROOT_PASSWORD: 'osmentos'
        volumes:
          - ./mysqllab:/var/lib/mysqllab
          - ./sqllab:/docker-entrypoint-initdb.d
        networks:
          - server_kafka_net

networks:
   server_kafka_net:
     external: true