version: '3.7'
services:
    web:
        build: .
        ports:
            - "5004:5004"
        volumes:
            - .:/code
        command: python ./app/app.py
        networks:
          - server_kafka_net

networks:
   server_kafka_net:
     external: true