# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: library.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='library.proto',
  package='library',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rlibrary.proto\x12\x07library\"(\n\x15GetBookDetailsRequest\x12\x0f\n\x07\x62ook_id\x18\x01 \x01(\x05\"e\n\x13GetBookDetailsReply\x12\x11\n\tbook_name\x18\x01 \x01(\t\x12\x13\n\x0b\x61uthor_name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x11\n\tcondition\x18\x04 \x01(\t\"\x1a\n\x18GetAvailableBooksRequest\"+\n\x16GetAvailableBooksReply\x12\x11\n\tbook_name\x18\x01 \x01(\t2\xb6\x01\n\x07Library\x12P\n\x0eGetBookDetails\x12\x1e.library.GetBookDetailsRequest\x1a\x1c.library.GetBookDetailsReply\"\x00\x12Y\n\x11GetAvailableBooks\x12!.library.GetAvailableBooksRequest\x1a\x1f.library.GetAvailableBooksReply\"\x00\x62\x06proto3'
)




_GETBOOKDETAILSREQUEST = _descriptor.Descriptor(
  name='GetBookDetailsRequest',
  full_name='library.GetBookDetailsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='book_id', full_name='library.GetBookDetailsRequest.book_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=66,
)


_GETBOOKDETAILSREPLY = _descriptor.Descriptor(
  name='GetBookDetailsReply',
  full_name='library.GetBookDetailsReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='book_name', full_name='library.GetBookDetailsReply.book_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='author_name', full_name='library.GetBookDetailsReply.author_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='description', full_name='library.GetBookDetailsReply.description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='condition', full_name='library.GetBookDetailsReply.condition', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=169,
)


_GETAVAILABLEBOOKSREQUEST = _descriptor.Descriptor(
  name='GetAvailableBooksRequest',
  full_name='library.GetAvailableBooksRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=171,
  serialized_end=197,
)


_GETAVAILABLEBOOKSREPLY = _descriptor.Descriptor(
  name='GetAvailableBooksReply',
  full_name='library.GetAvailableBooksReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='book_name', full_name='library.GetAvailableBooksReply.book_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=199,
  serialized_end=242,
)

DESCRIPTOR.message_types_by_name['GetBookDetailsRequest'] = _GETBOOKDETAILSREQUEST
DESCRIPTOR.message_types_by_name['GetBookDetailsReply'] = _GETBOOKDETAILSREPLY
DESCRIPTOR.message_types_by_name['GetAvailableBooksRequest'] = _GETAVAILABLEBOOKSREQUEST
DESCRIPTOR.message_types_by_name['GetAvailableBooksReply'] = _GETAVAILABLEBOOKSREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetBookDetailsRequest = _reflection.GeneratedProtocolMessageType('GetBookDetailsRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETBOOKDETAILSREQUEST,
  '__module__' : 'library_pb2'
  # @@protoc_insertion_point(class_scope:library.GetBookDetailsRequest)
  })
_sym_db.RegisterMessage(GetBookDetailsRequest)

GetBookDetailsReply = _reflection.GeneratedProtocolMessageType('GetBookDetailsReply', (_message.Message,), {
  'DESCRIPTOR' : _GETBOOKDETAILSREPLY,
  '__module__' : 'library_pb2'
  # @@protoc_insertion_point(class_scope:library.GetBookDetailsReply)
  })
_sym_db.RegisterMessage(GetBookDetailsReply)

GetAvailableBooksRequest = _reflection.GeneratedProtocolMessageType('GetAvailableBooksRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETAVAILABLEBOOKSREQUEST,
  '__module__' : 'library_pb2'
  # @@protoc_insertion_point(class_scope:library.GetAvailableBooksRequest)
  })
_sym_db.RegisterMessage(GetAvailableBooksRequest)

GetAvailableBooksReply = _reflection.GeneratedProtocolMessageType('GetAvailableBooksReply', (_message.Message,), {
  'DESCRIPTOR' : _GETAVAILABLEBOOKSREPLY,
  '__module__' : 'library_pb2'
  # @@protoc_insertion_point(class_scope:library.GetAvailableBooksReply)
  })
_sym_db.RegisterMessage(GetAvailableBooksReply)



_LIBRARY = _descriptor.ServiceDescriptor(
  name='Library',
  full_name='library.Library',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=245,
  serialized_end=427,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetBookDetails',
    full_name='library.Library.GetBookDetails',
    index=0,
    containing_service=None,
    input_type=_GETBOOKDETAILSREQUEST,
    output_type=_GETBOOKDETAILSREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetAvailableBooks',
    full_name='library.Library.GetAvailableBooks',
    index=1,
    containing_service=None,
    input_type=_GETAVAILABLEBOOKSREQUEST,
    output_type=_GETAVAILABLEBOOKSREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_LIBRARY)

DESCRIPTOR.services_by_name['Library'] = _LIBRARY

# @@protoc_insertion_point(module_scope)
