# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/availablerequestmesg.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/availablerequestmesg.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n!protos/availablerequestmesg.proto\"\x16\n\x14\x41vailableRequestMesgb\x06proto3'
)




_AVAILABLEREQUESTMESG = _descriptor.Descriptor(
  name='AvailableRequestMesg',
  full_name='AvailableRequestMesg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=59,
)

DESCRIPTOR.message_types_by_name['AvailableRequestMesg'] = _AVAILABLEREQUESTMESG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AvailableRequestMesg = _reflection.GeneratedProtocolMessageType('AvailableRequestMesg', (_message.Message,), {
  'DESCRIPTOR' : _AVAILABLEREQUESTMESG,
  '__module__' : 'protos.availablerequestmesg_pb2'
  # @@protoc_insertion_point(class_scope:AvailableRequestMesg)
  })
_sym_db.RegisterMessage(AvailableRequestMesg)


# @@protoc_insertion_point(module_scope)
