# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/availablebookfields.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/availablebookfields.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n protos/availablebookfields.proto\"=\n\x13\x41vailablebookFields\x12\x11\n\tbook_name\x18\x01 \x01(\t\x12\x13\n\x0b\x61uthor_name\x18\x02 \x01(\tb\x06proto3'
)




_AVAILABLEBOOKFIELDS = _descriptor.Descriptor(
  name='AvailablebookFields',
  full_name='AvailablebookFields',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='book_name', full_name='AvailablebookFields.book_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='author_name', full_name='AvailablebookFields.author_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=97,
)

DESCRIPTOR.message_types_by_name['AvailablebookFields'] = _AVAILABLEBOOKFIELDS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AvailablebookFields = _reflection.GeneratedProtocolMessageType('AvailablebookFields', (_message.Message,), {
  'DESCRIPTOR' : _AVAILABLEBOOKFIELDS,
  '__module__' : 'protos.availablebookfields_pb2'
  # @@protoc_insertion_point(class_scope:AvailablebookFields)
  })
_sym_db.RegisterMessage(AvailablebookFields)


# @@protoc_insertion_point(module_scope)
