# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/availableresponsemesg.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos import availablebookfields_pb2 as protos_dot_availablebookfields__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/availableresponsemesg.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\"protos/availableresponsemesg.proto\x1a protos/availablebookfields.proto\"E\n\x15\x41vailableResponseMesg\x12,\n\x0e\x61vailablebooks\x18\x01 \x03(\x0b\x32\x14.AvailablebookFieldsb\x06proto3'
  ,
  dependencies=[protos_dot_availablebookfields__pb2.DESCRIPTOR,])




_AVAILABLERESPONSEMESG = _descriptor.Descriptor(
  name='AvailableResponseMesg',
  full_name='AvailableResponseMesg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='availablebooks', full_name='AvailableResponseMesg.availablebooks', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=141,
)

_AVAILABLERESPONSEMESG.fields_by_name['availablebooks'].message_type = protos_dot_availablebookfields__pb2._AVAILABLEBOOKFIELDS
DESCRIPTOR.message_types_by_name['AvailableResponseMesg'] = _AVAILABLERESPONSEMESG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AvailableResponseMesg = _reflection.GeneratedProtocolMessageType('AvailableResponseMesg', (_message.Message,), {
  'DESCRIPTOR' : _AVAILABLERESPONSEMESG,
  '__module__' : 'protos.availableresponsemesg_pb2'
  # @@protoc_insertion_point(class_scope:AvailableResponseMesg)
  })
_sym_db.RegisterMessage(AvailableResponseMesg)


# @@protoc_insertion_point(module_scope)
