# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/bookrecordresponsemesg.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/bookrecordresponsemesg.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n#protos/bookrecordresponsemesg.proto\"\'\n\x16\x42ookRecordResponseMesg\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\x62\x06proto3'
)




_BOOKRECORDRESPONSEMESG = _descriptor.Descriptor(
  name='BookRecordResponseMesg',
  full_name='BookRecordResponseMesg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='count', full_name='BookRecordResponseMesg.count', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=78,
)

DESCRIPTOR.message_types_by_name['BookRecordResponseMesg'] = _BOOKRECORDRESPONSEMESG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BookRecordResponseMesg = _reflection.GeneratedProtocolMessageType('BookRecordResponseMesg', (_message.Message,), {
  'DESCRIPTOR' : _BOOKRECORDRESPONSEMESG,
  '__module__' : 'protos.bookrecordresponsemesg_pb2'
  # @@protoc_insertion_point(class_scope:BookRecordResponseMesg)
  })
_sym_db.RegisterMessage(BookRecordResponseMesg)


# @@protoc_insertion_point(module_scope)
