# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/bookdetailsrequestmesg.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/bookdetailsrequestmesg.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n#protos/bookdetailsrequestmesg.proto\")\n\x16\x42ookDetailsRequestmesg\x12\x0f\n\x07\x62ook_id\x18\x01 \x01(\x05\x62\x06proto3'
)




_BOOKDETAILSREQUESTMESG = _descriptor.Descriptor(
  name='BookDetailsRequestmesg',
  full_name='BookDetailsRequestmesg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='book_id', full_name='BookDetailsRequestmesg.book_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=80,
)

DESCRIPTOR.message_types_by_name['BookDetailsRequestmesg'] = _BOOKDETAILSREQUESTMESG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BookDetailsRequestmesg = _reflection.GeneratedProtocolMessageType('BookDetailsRequestmesg', (_message.Message,), {
  'DESCRIPTOR' : _BOOKDETAILSREQUESTMESG,
  '__module__' : 'protos.bookdetailsrequestmesg_pb2'
  # @@protoc_insertion_point(class_scope:BookDetailsRequestmesg)
  })
_sym_db.RegisterMessage(BookDetailsRequestmesg)


# @@protoc_insertion_point(module_scope)
