# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/bookrecordrequestmesg.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/bookrecordrequestmesg.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\"protos/bookrecordrequestmesg.proto\"(\n\x15\x42ookRecordRequestMesg\x12\x0f\n\x07\x62ook_id\x18\x01 \x01(\x05\x62\x06proto3'
)




_BOOKRECORDREQUESTMESG = _descriptor.Descriptor(
  name='BookRecordRequestMesg',
  full_name='BookRecordRequestMesg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='book_id', full_name='BookRecordRequestMesg.book_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=78,
)

DESCRIPTOR.message_types_by_name['BookRecordRequestMesg'] = _BOOKRECORDREQUESTMESG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BookRecordRequestMesg = _reflection.GeneratedProtocolMessageType('BookRecordRequestMesg', (_message.Message,), {
  'DESCRIPTOR' : _BOOKRECORDREQUESTMESG,
  '__module__' : 'protos.bookrecordrequestmesg_pb2'
  # @@protoc_insertion_point(class_scope:BookRecordRequestMesg)
  })
_sym_db.RegisterMessage(BookRecordRequestMesg)


# @@protoc_insertion_point(module_scope)
