# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/getbookdetails.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos import availablerequestmesg_pb2 as protos_dot_availablerequestmesg__pb2
from protos import availableresponsemesg_pb2 as protos_dot_availableresponsemesg__pb2
from protos import bookdetailsrequestmesg_pb2 as protos_dot_bookdetailsrequestmesg__pb2
from protos import bookdetailsresponsemesg_pb2 as protos_dot_bookdetailsresponsemesg__pb2
from protos import bookrecordrequestmesg_pb2 as protos_dot_bookrecordrequestmesg__pb2
from protos import bookrecordresponsemesg_pb2 as protos_dot_bookrecordresponsemesg__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/getbookdetails.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1bprotos/getbookdetails.proto\x1a!protos/availablerequestmesg.proto\x1a\"protos/availableresponsemesg.proto\x1a#protos/bookdetailsrequestmesg.proto\x1a$protos/bookdetailsresponsemesg.proto\x1a\"protos/bookrecordrequestmesg.proto\x1a#protos/bookrecordresponsemesg.proto2\xd8\x01\n\x0eGetBookdetails\x12\x41\n\x0e\x61vailableBooks\x12\x15.AvailableRequestMesg\x1a\x16.AvailableResponseMesg\"\x00\x12\x42\n\x0b\x62ookDetails\x12\x17.BookDetailsRequestmesg\x1a\x18.BookDetailsResponseMesg\"\x00\x12?\n\nbookRecord\x12\x16.BookRecordRequestMesg\x1a\x17.BookRecordResponseMesg\"\x00\x62\x06proto3'
  ,
  dependencies=[protos_dot_availablerequestmesg__pb2.DESCRIPTOR,protos_dot_availableresponsemesg__pb2.DESCRIPTOR,protos_dot_bookdetailsrequestmesg__pb2.DESCRIPTOR,protos_dot_bookdetailsresponsemesg__pb2.DESCRIPTOR,protos_dot_bookrecordrequestmesg__pb2.DESCRIPTOR,protos_dot_bookrecordresponsemesg__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_GETBOOKDETAILS = _descriptor.ServiceDescriptor(
  name='GetBookdetails',
  full_name='GetBookdetails',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=251,
  serialized_end=467,
  methods=[
  _descriptor.MethodDescriptor(
    name='availableBooks',
    full_name='GetBookdetails.availableBooks',
    index=0,
    containing_service=None,
    input_type=protos_dot_availablerequestmesg__pb2._AVAILABLEREQUESTMESG,
    output_type=protos_dot_availableresponsemesg__pb2._AVAILABLERESPONSEMESG,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='bookDetails',
    full_name='GetBookdetails.bookDetails',
    index=1,
    containing_service=None,
    input_type=protos_dot_bookdetailsrequestmesg__pb2._BOOKDETAILSREQUESTMESG,
    output_type=protos_dot_bookdetailsresponsemesg__pb2._BOOKDETAILSRESPONSEMESG,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='bookRecord',
    full_name='GetBookdetails.bookRecord',
    index=2,
    containing_service=None,
    input_type=protos_dot_bookrecordrequestmesg__pb2._BOOKRECORDREQUESTMESG,
    output_type=protos_dot_bookrecordresponsemesg__pb2._BOOKRECORDRESPONSEMESG,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GETBOOKDETAILS)

DESCRIPTOR.services_by_name['GetBookdetails'] = _GETBOOKDETAILS

# @@protoc_insertion_point(module_scope)
