# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos import availablerequestmesg_pb2 as protos_dot_availablerequestmesg__pb2
from protos import availableresponsemesg_pb2 as protos_dot_availableresponsemesg__pb2
from protos import bookdetailsrequestmesg_pb2 as protos_dot_bookdetailsrequestmesg__pb2
from protos import bookdetailsresponsemesg_pb2 as protos_dot_bookdetailsresponsemesg__pb2
from protos import bookrecordrequestmesg_pb2 as protos_dot_bookrecordrequestmesg__pb2
from protos import bookrecordresponsemesg_pb2 as protos_dot_bookrecordresponsemesg__pb2


class GetBookdetailsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.availableBooks = channel.unary_unary(
                '/GetBookdetails/availableBooks',
                request_serializer=protos_dot_availablerequestmesg__pb2.AvailableRequestMesg.SerializeToString,
                response_deserializer=protos_dot_availableresponsemesg__pb2.AvailableResponseMesg.FromString,
                )
        self.bookDetails = channel.unary_unary(
                '/GetBookdetails/bookDetails',
                request_serializer=protos_dot_bookdetailsrequestmesg__pb2.BookDetailsRequestmesg.SerializeToString,
                response_deserializer=protos_dot_bookdetailsresponsemesg__pb2.BookDetailsResponseMesg.FromString,
                )
        self.bookRecord = channel.unary_unary(
                '/GetBookdetails/bookRecord',
                request_serializer=protos_dot_bookrecordrequestmesg__pb2.BookRecordRequestMesg.SerializeToString,
                response_deserializer=protos_dot_bookrecordresponsemesg__pb2.BookRecordResponseMesg.FromString,
                )


class GetBookdetailsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def availableBooks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def bookDetails(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def bookRecord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GetBookdetailsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'availableBooks': grpc.unary_unary_rpc_method_handler(
                    servicer.availableBooks,
                    request_deserializer=protos_dot_availablerequestmesg__pb2.AvailableRequestMesg.FromString,
                    response_serializer=protos_dot_availableresponsemesg__pb2.AvailableResponseMesg.SerializeToString,
            ),
            'bookDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.bookDetails,
                    request_deserializer=protos_dot_bookdetailsrequestmesg__pb2.BookDetailsRequestmesg.FromString,
                    response_serializer=protos_dot_bookdetailsresponsemesg__pb2.BookDetailsResponseMesg.SerializeToString,
            ),
            'bookRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.bookRecord,
                    request_deserializer=protos_dot_bookrecordrequestmesg__pb2.BookRecordRequestMesg.FromString,
                    response_serializer=protos_dot_bookrecordresponsemesg__pb2.BookRecordResponseMesg.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'GetBookdetails', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GetBookdetails(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def availableBooks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GetBookdetails/availableBooks',
            protos_dot_availablerequestmesg__pb2.AvailableRequestMesg.SerializeToString,
            protos_dot_availableresponsemesg__pb2.AvailableResponseMesg.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def bookDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GetBookdetails/bookDetails',
            protos_dot_bookdetailsrequestmesg__pb2.BookDetailsRequestmesg.SerializeToString,
            protos_dot_bookdetailsresponsemesg__pb2.BookDetailsResponseMesg.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def bookRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GetBookdetails/bookRecord',
            protos_dot_bookrecordrequestmesg__pb2.BookRecordRequestMesg.SerializeToString,
            protos_dot_bookrecordresponsemesg__pb2.BookRecordResponseMesg.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
